services:
  db:
    image: postgres:latest
    network_mode: host
    container_name: rinha2023q3_db_1
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: '1.5GB'

  api1:
    # image: rinha2023q3:latest
    build: .
    restart: always
    network_mode: host
    container_name: rinha2023q3_1
    environment:
      PORT: "6969"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "6969"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  api2:
    # image: rinha2023q3:latest
    build: .
    restart: always
    network_mode: host
    container_name: rinha2023q3_2
    environment:
      PORT: "4200"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "6969"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
