services:
  db:
    image: postgres:latest
    network_mode: host
    container_name: rinha2023_db_1
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./configs/create_pessoas_table.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  cache:
    image: redis:latest
    network_mode: host
    container_name: rinha2023_cache
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  api1:
    # image: rinha2023:latest
    build: .
    restart: always
    network_mode: host
    container_name: rinha2023_1
    environment:
      PORT: "6969"
      API_NAME: "api1"
      CACHE_HOST: "localhost"
      CACHE_PORT: "6379"
      CACHE_PASSWORD: ""
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    expose:
      - "6969"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2:
    # image: rinha2023:latest
    build: .
    restart: always
    network_mode: host
    container_name: rinha2023_2
    environment:
      PORT: "4200"
      API_NAME: "api2"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx-logs:/var/log/nginx
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    depends_on:
      - api1
      - api2
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
