services:
  db:
    image: postgres:latest
    network_mode: host
    container_name: rinha2023q3_db_1
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  api1:
    image: rinha2023q3:latest
    restart: always
    network_mode: host
    container_name: rinha2023q3_1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "6969"

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"
