worker_processes auto;

events {
    worker_connections 10240;
}

http {
    sendfile on;

    upstream api_backend {
        keepalive 256;
        keepalive_requests 10000;

        server localhost:6969;
        server localhost:4200;
    }

    server {
        listen 9999;
        access_log off;
        error_log /dev/null crit;

        server_name localhost;
        location / {
            proxy_pass http://api_backend;
            proxy_buffering on;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection "";
        }
    }
}
