global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: node
  static_configs:
  - targets: ['localhost:9100']

- job_name: rinha2023_metrics
  metrics_path: /metrics
  static_configs:
  - targets: ['localhost:6969']
    labels:
      replica: A
  - targets: ['localhost:4200']
    labels:
      replica: B
